### ISSUE TITLE
Outdated code repo URL on toolsadmin.wikimedia.org

### ISSUE THREAD

**Issue by aklapper** [cluebotng/bot#14]
https://toolsadmin.wikimedia.org/tools/id/cluebotng states that the source code is at https://github.com/cluebotng/cluebotng 

That repository has been archived. The URL should be updated to https://github.com/cluebotng/

**Comment by DamianZaremba** [comment]
https://toolsadmin.wikimedia.org/tools/id/cluebotng/info/id/1262/history?version_id2=3167&version_id1=1997
